const sampleUsers = [
  {
    name: "Alice Johnson",
    email: "alice.johnson@email.com",
    location: "New York, NY",
    profilePhoto: "https://example.com/photos/alice.jpg",
    skillOffered: ["Web Development", "Graphic Design", "Photography"],
    skillWanted: ["Cooking", "Yoga Instruction", "Spanish Language"],
    isPublic: true,
    role: "user",
    rating: 4.5,
    totalSwaps: 12,
    joinDate: new Date("2023-01-15"),
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-10")
  },
  {
    name: "Bob Smith",
    email: "bob.smith@email.com",
    location: "Los Angeles, CA",
    profilePhoto: "https://example.com/photos/bob.jpg",
    skillOffered: ["Carpentry", "Home Repair", "Gardening"],
    skillWanted: ["Web Development", "Digital Marketing", "Photo Editing"],
    isPublic: true,
    role: "user",
    rating: 4.8,
    totalSwaps: 25,
    joinDate: new Date("2022-08-22"),
    createdAt: new Date("2022-08-22"),
    updatedAt: new Date("2024-01-08")
  },
  {
    name: "Carol Davis",
    email: "carol.davis@email.com",
    location: "Chicago, IL",
    profilePhoto: "https://example.com/photos/carol.jpg",
    skillOffered: ["Cooking", "Baking", "Nutrition Counseling"],
    skillWanted: ["Graphic Design", "Social Media Management", "Video Editing"],
    isPublic: false,
    role: "user",
    rating: 4.2,
    totalSwaps: 8,
    joinDate: new Date("2023-05-10"),
    createdAt: new Date("2023-05-10"),
    updatedAt: new Date("2024-01-05")
  },
  {
    name: "David Wilson",
    email: "david.wilson@email.com",
    location: "Miami, FL",
    profilePhoto: "https://example.com/photos/david.jpg",
    skillOffered: ["Spanish Language", "Portuguese Language", "Translation"],
    skillWanted: ["Home Repair", "Car Maintenance", "Fitness Training"],
    isPublic: true,
    role: "user",
    rating: 4.9,
    totalSwaps: 18,
    joinDate: new Date("2023-03-18"),
    createdAt: new Date("2023-03-18"),
    updatedAt: new Date("2024-01-12")
  },
  {
    name: "Eva Martinez",
    email: "eva.martinez@email.com",
    location: "Austin, TX",
    profilePhoto: "https://example.com/photos/eva.jpg",
    skillOffered: ["Yoga Instruction", "Meditation", "Wellness Coaching"],
    skillWanted: ["Gardening", "Painting", "Music Lessons"],
    isPublic: true,
    role: "admin",
    rating: 5.0,
    totalSwaps: 32,
    joinDate: new Date("2022-01-05"),
    createdAt: new Date("2022-01-05"),
    updatedAt: new Date("2024-01-15")
  },
  {
    name: "Frank Brown",
    email: "frank.brown@email.com",
    location: "Seattle, WA",
    profilePhoto: "https://example.com/photos/frank.jpg",
    skillOffered: ["Music Production", "Guitar Lessons", "Audio Engineering"],
    skillWanted: ["Cooking", "Baking", "Nutrition"],
    isPublic: true,
    role: "user",
    rating: 4.3,
    totalSwaps: 15,
    joinDate: new Date("2023-07-30"),
    createdAt: new Date("2023-07-30"),
    updatedAt: new Date("2024-01-09")
  },
  {
    name: "Grace Lee",
    email: "grace.lee@email.com",
    location: "Portland, OR",
    profilePhoto: "https://example.com/photos/grace.jpg",
    skillOffered: ["Graphic Design", "UI/UX Design", "Illustration"],
    skillWanted: ["Yoga", "Meditation", "Dance"],
    isPublic: false,
    role: "user",
    rating: 4.7,
    totalSwaps: 21,
    joinDate: new Date("2022-11-12"),
    createdAt: new Date("2022-11-12"),
    updatedAt: new Date("2024-01-07")
  },
  {
    name: "Henry Chen",
    email: "henry.chen@email.com",
    location: "Boston, MA",
    profilePhoto: "https://example.com/photos/henry.jpg",
    skillOffered: ["Math Tutoring", "Physics Tutoring", "Programming"],
    skillWanted: ["Photography", "Video Editing", "Public Speaking"],
    isPublic: true,
    role: "user",
    rating: 4.6,
    totalSwaps: 14,
    joinDate: new Date("2023-09-05"),
    createdAt: new Date("2023-09-05"),
    updatedAt: new Date("2024-01-11")
  },
  {
    name: "Irene Garcia",
    email: "irene.garcia@email.com",
    location: "Denver, CO",
    profilePhoto: "https://example.com/photos/irene.jpg",
    skillOffered: ["Photography", "Photo Editing", "Videography"],
    skillWanted: ["Web Development", "Graphic Design", "Marketing"],
    isPublic: true,
    role: "user",
    rating: 4.4,
    totalSwaps: 9,
    joinDate: new Date("2023-12-01"),
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2024-01-14")
  },
  {
    name: "Jack Taylor",
    email: "jack.taylor@email.com",
    location: "San Francisco, CA",
    profilePhoto: "https://example.com/photos/jack.jpg",
    skillOffered: ["Fitness Training", "Nutrition Planning", "Personal Coaching"],
    skillWanted: ["Music Production", "Language Learning", "Art"],
    isPublic: true,
    role: "user",
    rating: 4.1,
    totalSwaps: 6,
    joinDate: new Date("2024-01-02"),
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-13")
  }
];

module.exports = { data: sampleUsers };